//! Native monitored text to the original source-linked, two-key publication.
//! No raw generated bytes leave this consumer before the original effect gate.
#[path = "generated/recipe.rs"]
mod recipe;
#[path = "generated/recovery.rs"]
mod recovery;
#[path = "generated/finish.rs"]
mod finish;
use recipe::Loaded;
use super::super::{Config, Deadline, Duration, ElapsedTick, ExecuteServices, FileOversight,
    FileSupervisedDriver, Instant, PeerProfile, RecoveryReserve, RunResult, cleanup,
    clock, control::Control, debug, execute_serviced, plus, stop};
use fa_reference::action::consequence::activation::monitor::decoder::sampled::generation::GenerationFinish;
use fa_reference::action::consequence::delivery::persistent::observed::decoder::text::FileTextGenerationCommand;
use fa_reference::action::consequence::delivery::persistent::observed::stream::generated::FileTextMessageRequest;
use fa_reference::action::consequence::oversight::actor::{ActorOutcome, Knowledge};
use fa_reference::action::consequence::oversight::actor_wire::{ActorWire, Command, encode_command};
use fa_reference::action::consequence::delivery::persistent::requests::actor::FileGeneratedTextActorPort;
use fa_reference::Error;
use fa_reference::action::consequence::delivery::persistent::JournalError;
use std::io::Write;
use std::path::Path;

const USAGE: &str = "create-generated CONFIG GENERATION_RECIPE REVIEWER_PROFILE [--after REQUEST_ID | --continue-generation] | create-generated CONFIG GENERATION_RECIPE --resume | create-generated CONFIG ORIGINAL_RECIPE REVIEWER_PROFILE --finish REQUEST_ID";

pub(super) fn command(args: &[String], credibility: Option<&Path>) -> Result<(), String> {
    if args.iter().any(|arg| arg == "--finish") { return finish::command(args, credibility); }
    if !matches!(args.len(), 4 | 5 | 6) || args[0] != "create-generated" || credibility.is_some() {
        return Err(USAGE.into());
    }
    // Closed option admission precedes all configuration/model reads and I/O.
    let after = if args.len() == 6 {
        if args[4] != "--after" || args[3].starts_with("--")
            || args[5].is_empty() || !args[5].bytes().all(|byte| byte.is_ascii_digit()) {
            return Err(USAGE.into());
        }
        let id = args[5].parse::<u64>().map_err(|_| USAGE.to_owned())?;
        if id == 0 { return Err(USAGE.into()); }
        Some(id)
    } else { None };
    let recover_generation = args.len() == 5;
    if recover_generation && (args[4] != "--continue-generation" || args[3].starts_with("--")) {
        return Err(USAGE.into());
    }
    if args[3].starts_with("--") && args[3] != "--resume" { return Err(USAGE.into()); }
    let config = Config::read(Path::new(&args[1]))?;
    if args[3] == "--resume" {
        let loaded = recipe::load(Path::new(&args[2]), &config)?;
        let result = recovery::resume(config, loaded, clock)?;
        return emit(result, &mut std::io::stdout().lock());
    }
    if args[3].starts_with("--") { return Err(USAGE.into()); }
    let peers = PeerProfile::read(Path::new(&args[3]))?;
    peers.check_host(&config)?;
    let loaded = recipe::load(Path::new(&args[2]), &config)?;
    let result = match after {
        Some(request) => continue_after(config, loaded, &peers, request, clock)?,
        None if recover_generation => continue_generation(config, loaded, &peers, clock)?,
        None => create(config, loaded, &peers, clock)?,
    };
    emit(result, &mut std::io::stdout().lock())
}

// The only stdout value is the ORIGINAL restricted actor response. Raw prompt,
// native output, source diagnostics, monitor scores and ballots are never printed.
fn emit(result: RunResult, output: &mut impl Write) -> Result<(), String> {
    output.write_all(&result.response.encode()).and_then(|()| output.write_all(b"\n"))
        .and_then(|()| output.flush()).map_err(|error| {
            format!("original response output failed: {error}; no effect retry was sent")
        })?;
    if let Some(error) = result.failure { return Err(error); }
    if result.cleanup_pending != 0 {
        return Err(format!("{} direct helper children lack reaping confirmation", result.cleanup_pending));
    }
    if !matches!(result.response.result,
        Ok(Knowledge::Known { value: ActorOutcome::Executed, .. }))
    { return Err("native publication is not confirmed; inspect the original response".into()); }
    Ok(())
}

fn create<F>(config: Config, loaded: Loaded, peers: &PeerProfile, time: F)
    -> Result<RunResult, String>
where F: FnMut() -> ElapsedTick {
    run(config, loaded, peers, Start::New, time)
}

fn continue_after<F>(config: Config, loaded: Loaded, peers: &PeerProfile, after: u64, time: F)
    -> Result<RunResult, String>
where F: FnMut() -> ElapsedTick {
    run(config, loaded, peers, Start::After(after), time)
}

fn continue_generation<F>(config: Config, loaded: Loaded, peers: &PeerProfile, time: F)
    -> Result<RunResult, String>
where F: FnMut() -> ElapsedTick {
    run(config, loaded, peers, Start::RecoverGeneration, time)
}

#[derive(Clone, Copy)]
enum Start { New, After(u64), RecoverGeneration }

// All three modes share EVERY token/source/stop/review/publication step.
// Only the initial owner and native intent differ; there is no second effect path.
fn run<F>(mut config: Config, loaded: Loaded, peers: &PeerProfile,
    origin: Start, mut time: F) -> Result<RunResult, String>
where F: FnMut() -> ElapsedTick {
    peers.check_host(&config)?;
    loaded.check_host(&config)?;
    if matches!(origin, Start::After(request) if request == 0 || request == loaded.request) {
        return Err("continuation needs a distinct nonzero prior request".into());
    }
    let start = time();
    let lifetime = loaded.ttl_ms.min(config.timing.runtime_ms);
    let deadline = Deadline { logical: plus(start, lifetime)?, started: Instant::now(),
        wall: Duration::from_millis(lifetime) };
    deadline.check(start)?;
    // Exclusive listener setup precedes store creation. It remains the SAME
    // stop service during inference, helper review and independent approval.
    let mut control = Control::new(&config, loaded.request, Some(peers))?;
    let (mut host, reviewer) = if !matches!(origin, Start::New) {
        recovery::open(&config, &loaded)?
    } else {
        FileOversight::create_generated_text_stream_with_reserve(
            &config.store, config.profile.clone(), loaded.stream, loaded.decoder.clone(),
            loaded.tokenizer.clone(), RecoveryReserve::terminal()).map_err(debug)?
    };
    let prepared = match origin {
        Start::New => {
            host.enable_file_source(host.revision(), config.source_policy).map_err(debug)?;
            None
        }
        Start::After(_) | Start::RecoverGeneration => {
            // BOTH modes make a first submission, never retry an existing effect.
            match host.request_status(loaded.request) {
                Err(JournalError::Contract(Error::Missing)) => {},
                Ok(_) => return Err("native request already exists; use --resume for its original receipt".into()),
                Err(error) => return Err(debug(error)),
            }
            host.check_credibility().map_err(debug)?;
            let command = match origin {
                Start::After(after) => host.prepare_decoder_text_continuation(after,
                    loaded.generation, loaded.text.clone()).map_err(debug)?,
                Start::RecoverGeneration => host.prepare_decoder_text_publication_recovery(
                    loaded.generation, &loaded.text).map_err(debug)?,
                Start::New => unreachable!("creation has no recovered intent"),
            };
            Some(command)
        }
    };
    let (port, supervisor) = host.into_generated_text_actor_gateway().map_err(debug)?;
    let mut driver = FileSupervisedDriver::new(supervisor);
    let mut wire = ActorWire::new(port);
    let work = (|| {
        if control.checkpoint(&mut driver, &reviewer, &deadline, &mut time)? { return Ok(()); }
        refresh(&mut driver, &mut config, &deadline, &mut time)?;
        {
            let mut host = driver.supervisor_mut().host_mut().map_err(debug)?;
            let current = host.decoder_inspection().map_err(debug)?.numerical;
            if let Some(command) = prepared {
                // Fresh evidence and its post-read clock were committed above.
                // Resume preserves original KV/RNG, lifetime work and the entire
                // retained generation budget. It does not begin another intent.
                let revision = host.revision();
                host.resume_decoder(revision, current.actor_revision, current.position).map_err(debug)?;
                match origin {
                    Start::After(after) => {
                        let revision = host.revision();
                        host.begin_decoder_text_continuation(revision, after, command).map_err(debug)?;
                    }
                    Start::RecoverGeneration => {
                        // Recheck after source/resume, but do NOT recreate the
                        // command at the later numerical position or renew limits.
                        let original = host.prepare_decoder_text_publication_recovery(
                            loaded.generation, &loaded.text).map_err(debug)?;
                        if original != command { return Err("recovered native intent changed".into()); }
                    }
                    Start::New => unreachable!("creation has no recovered intent"),
                }
            } else {
                let command = FileTextGenerationCommand::new(loaded.generation,
                    current.actor_revision, current.position, loaded.text.clone()).map_err(debug)?;
                let revision = host.revision();
                host.begin_decoder_text(revision, command).map_err(debug)?;
            }
        }
        let generation_revision = loop {
            deadline.check(time())?;
            if control.checkpoint(&mut driver, &reviewer, &deadline, &mut time)? { return Ok(()); }
            let progress = driver.supervisor().host().map_err(debug)?
                .decoder_text_progress(loaded.generation).map_err(debug)?;
            if progress.is_complete() {
                if progress.finish() != Some(Ok(GenerationFinish::StopToken)) {
                    return Err(format!("native generation did not complete at a monitored stop: {:?}", progress.finish()));
                }
                break progress.generation_revision();
            }
            // A fresh registered observation and post-read clock precede EVERY
            // original token. Neither slow reads nor recovery can renew a lease
            // from a saved tick. The native gate performs the final admission.
            refresh(&mut driver, &mut config, &deadline, &mut time)?;
            let mut host = driver.supervisor_mut().host_mut().map_err(debug)?;
            let revision = host.revision();
            host.advance_decoder_text(revision, loaded.generation,
                progress.generation_revision()).map_err(debug)?;
        };
        let request = {
            let host = driver.supervisor().host().map_err(debug)?;
            FileTextMessageRequest { request: loaded.request, generation: loaded.generation,
                generation_revision, target: host.inspect().target,
                policy_epoch: host.inspect().control.ledger.epoch, deadline: deadline.logical }
        };
        // This envelope contains a source reference, NOT decoded output. The
        // original native-only stream checks full prompt review, Control-stop
        // semantics, current numerical predecessor, UTF-8 and cumulative charge.
        let proposal = FileGeneratedTextActorPort::encode_message(&request).map_err(debug)?;
        let document = encode_command(&Command::Submit { request: loaded.request, proposal }).map_err(debug)?;
        deadline.check(time())?;
        if control.checkpoint(&mut driver, &reviewer, &deadline, &mut time)? { return Ok(()); }
        let submitted = driver.exchange_generated_actor_from_file(&mut wire, &document,
            &mut config.source, &mut time).map_err(debug)?;
        if submitted.response.result.is_err() {
            return Err("original source-linked gateway refused generated publication".into());
        }
        let mut no_ingress = |_: &mut FileSupervisedDriver| Ok(false);
        execute_serviced(&mut driver, &reviewer, &mut config, loaded.request, &deadline,
            ExecuteServices { peers: Some(peers), publication: None, ingress: &mut no_ingress,
                stop: Some(control) }, &mut time)
    })();
    let failure = work.err().map(|error| match stop(&mut driver, loaded.request, &mut time) {
        Ok(()) => error, Err(stopping) => format!("{error}; stop/drain: {stopping}"),
    });
    let response = wire.exchange(&encode_command(&Command::Poll { request: loaded.request }).map_err(debug)?);
    let cleanup_pending = cleanup(driver, config.timing.cleanup_ms, config.timing.poll_ms);
    Ok(RunResult { response, failure, cleanup_pending })
}

fn refresh<F>(driver: &mut FileSupervisedDriver, config: &mut Config,
    deadline: &Deadline, time: &mut F) -> Result<(), String>
where F: FnMut() -> ElapsedTick {
    let before = time();
    deadline.check(before)?;
    let mut host = driver.supervisor_mut().host_mut().map_err(debug)?;
    let revision = host.revision();
    host.refresh_file_source(revision, &mut config.source, before).map_err(debug)?;
    let after = time();
    deadline.check(after)?;
    let revision = host.revision();
    host.observe_time(revision, after).map_err(debug)?;
    Ok(())
}

#[cfg(test)]
#[path = "generated/tests.rs"]
mod tests;

#[cfg(test)]
#[path = "generated/operations.rs"]
mod operations;
