//! Local gate driver. DSR owns the durable outer receipt and source freeze.
#![forbid(unsafe_code)]

mod admission;
#[cfg(test)]
mod admission_negative_tests;
mod json;
#[cfg(test)]
mod json_tests;
#[cfg(test)]
mod metadata_collection_tests;
#[cfg(test)]
mod metadata_path_tests;
mod registry_checks;
#[cfg(test)]
mod registry_negative_tests;
mod toolchain_identity;

use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode, Stdio};

const APPROVED_LOCK: &str = r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "fa-reference"
version = "0.2.0"

[[package]]
name = "xtask"
version = "0.2.0"
"#;

fn normalized_lines(text: &str) -> Vec<&str> {
    text.lines()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .collect()
}

fn check_lock(root: &Path) -> Result<(), String> {
    let content = fs::read_to_string(root.join("Cargo.lock")).map_err(|e| e.to_string())?;
    if normalized_lines(&content) != normalized_lines(APPROVED_LOCK) {
        return Err("Dependency graph changed. The initial zero-external-package gate must not be weakened; implement and review full source/feature admission before adding foundations.".into());
    }
    println!("PASS reference_lock: exactly fa-reference and xtask; no external packages");
    Ok(())
}

fn check_source(root: &Path) -> Result<(), String> {
    for path in [
        "crates/fa-reference/src/lib.rs",
        "xtask/src/main.rs",
        "registry/foundation_audit.json",
        "docs/DEPENDENCY_CONSTITUTION.md",
        "docs/LOCAL_RELEASE.md",
        "COMPREHENSIVE_PLAN_FOR_THE_DESIGN_OF_FRANKENALIGNMENT.md",
    ] {
        if !root.join(path).is_file() {
            return Err(format!("Required file is missing: {path}"));
        }
    }
    for path in ["crates/fa-reference/src/lib.rs", "xtask/src/main.rs"] {
        let text = fs::read_to_string(root.join(path)).map_err(|e| e.to_string())?;
        if !text.contains("#![forbid(unsafe_code)]") {
            return Err(format!("Missing crate-level unsafe prohibition: {path}"));
        }
    }
    println!("PASS source_inventory: required files and crate-level prohibitions present");
    Ok(())
}

fn run(root: &Path, program: &str, arguments: &[&str]) -> Result<(), String> {
    println!("EXECUTE {program} {}", arguments.join(" "));
    let status = Command::new(program)
        .args(arguments)
        .current_dir(root)
        .status()
        .map_err(|e| format!("Cannot execute {program}: {e}"))?;
    if !status.success() {
        return Err(format!(
            "{program} {} failed: {status}",
            arguments.join(" ")
        ));
    }
    println!("PASS executed_command: {program} {}", arguments.join(" "));
    Ok(())
}

fn contained_file(root: &Path, value: &json::Json) -> Result<(), String> {
    let path = value
        .as_str()
        .ok_or("Metadata file path must be a string")?;
    let resolved = fs::canonicalize(path)
        .map_err(|error| format!("Cannot resolve metadata file {path}: {error}"))?;
    if !resolved.starts_with(root) || !resolved.is_file() {
        return Err(format!(
            "Metadata file escapes workspace or is not a file: {path}"
        ));
    }
    Ok(())
}

// This checks real filesystem identities at collection time. It does not claim
// a complete Rust include/module closure or protect against concurrent mutation;
// the outer operator source freeze is still required.
fn check_metadata_paths(root: &Path, bytes: &[u8]) -> Result<(), String> {
    let root = fs::canonicalize(root).map_err(|error| error.to_string())?;
    let document = json::parse(bytes, json::Limits::default())
        .map_err(|error| format!("Metadata parse failed: {error}"))?;
    let metadata_root = document
        .get("workspace_root")
        .and_then(json::Json::as_str)
        .ok_or("Metadata workspace root missing")?;
    if fs::canonicalize(metadata_root).map_err(|error| error.to_string())? != root {
        return Err("Metadata belongs to a different workspace".into());
    }
    let packages = document
        .get("packages")
        .and_then(json::Json::as_array)
        .ok_or("Metadata packages missing")?;
    for package in packages {
        contained_file(
            &root,
            package
                .get("manifest_path")
                .ok_or("Manifest path missing")?,
        )?;
        let targets = package
            .get("targets")
            .and_then(json::Json::as_array)
            .ok_or("Metadata target list missing")?;
        for target in targets {
            contained_file(
                &root,
                target.get("src_path").ok_or("Target source path missing")?,
            )?;
        }
    }
    Ok(())
}

fn collect_metadata(root: &Path, target: &str) -> Result<Vec<u8>, String> {
    let arguments = [
        "metadata",
        "--format-version",
        "1",
        "--locked",
        "--offline",
        "--filter-platform",
        target,
    ];
    let manifest = root.join("Cargo.toml");
    println!(
        "EXECUTE cargo {} --manifest-path {}",
        arguments.join(" "),
        manifest.display()
    );
    let output = Command::new("cargo")
        .args(arguments)
        .arg("--manifest-path")
        .arg(&manifest)
        .current_dir(root)
        .stderr(Stdio::inherit())
        .output()
        .map_err(|error| format!("Cannot collect metadata for {target}: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "Metadata collection for {target} failed: {}",
            output.status
        ));
    }
    Ok(output.stdout)
}

fn check_admission(root: &Path) -> Result<(), String> {
    let bytes = fs::read(root.join("registry/dependency_policy.json"))
        .map_err(|error| format!("Cannot read dependency policy: {error}"))?;
    let policy = admission::parse_policy(&bytes)?;
    for profile in &policy.profiles {
        let target = profile.target.as_str();
        let metadata = collect_metadata(root, target)?;
        let report = admission::check(&metadata, &policy, target)?;
        if !report.is_admitted() {
            print!("{}", report.render());
            return Err(format!("Dependency admission refused for {target}"));
        }
        check_metadata_paths(root, &metadata)?;
        print!("{}", report.render());
        println!(
            "PASS collected_metadata_paths[{target}]: actual workspace, manifests and target source files"
        );
    }
    Ok(())
}

fn check_toolchain(root: &Path) -> Result<(), String> {
    let policy_bytes = fs::read(root.join("registry/dependency_policy.json"))
        .map_err(|error| format!("Cannot read toolchain qualification: {error}"))?;
    let policy = json::parse(&policy_bytes, json::Limits::default())
        .map_err(|error| format!("Invalid qualification policy: {error}"))?;
    let qualification = policy
        .get("operator_qualification")
        .ok_or("Missing operator toolchain qualification")?;
    let expected_commit = qualification
        .get("rustc_commit")
        .and_then(json::Json::as_str)
        .ok_or("Missing qualified rustc commit")?;
    let expected_host = qualification
        .get("host")
        .and_then(json::Json::as_str)
        .ok_or("Missing qualified operator host")?;
    println!("EXECUTE rustc -Vv");
    let output = Command::new("rustc")
        .arg("-Vv")
        .current_dir(root)
        .stderr(Stdio::inherit())
        .output()
        .map_err(|error| format!("Cannot collect rustc identity: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "rustc identity collection failed: {}",
            output.status
        ));
    }
    std::io::stdout()
        .write_all(&output.stdout)
        .map_err(|error| format!("Cannot retain rustc identity output: {error}"))?;
    toolchain_identity::check_verbose_version(&output.stdout, expected_commit, expected_host)?;
    println!(
        "PASS qualified_rustc_identity: {expected_commit} on {expected_host}; compiler-reported identity only"
    );
    Ok(())
}

fn check_registries(root: &Path) -> Result<(), String> {
    let report = registry_checks::check_repository(root);
    for finding in &report.findings {
        eprintln!(
            "REFUSE registry[{}] {} {} {}: {}",
            finding.file,
            finding.id.as_deref().unwrap_or("<document>"),
            finding.code,
            finding.location,
            finding.detail
        );
    }
    if !report.is_clean() {
        return Err(format!(
            "Registry core refused {} structural findings",
            report.findings.len()
        ));
    }
    println!(
        "PASS registry_core: IDs, roadmap DAG, declared links, retained files and scoped source test declarations; not execution or invariant proof"
    );
    Ok(())
}

fn execute() -> Result<(), String> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .ok_or("Missing workspace parent")?
        .to_path_buf();
    let args: Vec<_> = env::args().skip(1).collect();
    match args.as_slice() {
        [command] if command == "check" => {
            check_lock(&root)?;
            check_source(&root)?;
            check_toolchain(&root)?;
            check_admission(&root)?;
            check_registries(&root)?;
            run(&root, "cargo", &["fmt", "--all", "--check"])?;
            run(&root, "cargo", &["check", "--workspace", "--all-targets", "--frozen"])?;
            run(&root, "cargo", &["clippy", "--workspace", "--all-targets", "--frozen", "--", "-D", "warnings"])?;
            run(&root, "cargo", &["test", "--workspace", "--all-targets", "--frozen"])?;
            run(&root, "cargo", &["test", "--workspace", "--doc", "--frozen"])?;
            println!("PASS local_reference_gate; not a production-readiness or signed-release claim");
            Ok(())
        }
        [command] if command == "inventory" => {
            check_lock(&root)?;
            check_source(&root)?;
            println!("INVENTORY ONLY: compilation, tests, source freezing and release verification were not performed by this command");
            Ok(())
        }
        [command] if command == "release-check" => {
            Err("Release blocked: no qualified production broker, frozen release toolchain, foundation closure, target matrix or signed proof closure exists in design draft 0.2.".into())
        }
        _ => Err("Usage: cargo xtask check | inventory | release-check".into()),
    }
}

fn main() -> ExitCode {
    match execute() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("FAIL: {error}");
            ExitCode::FAILURE
        }
    }
}
