//! Local gate driver. DSR owns the durable outer receipt and source freeze.
#![forbid(unsafe_code)]

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

const APPROVED_LOCK: &str = r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "fa-reference"
version = "0.2.0"

[[package]]
name = "xtask"
version = "0.2.0"
"#;

fn normalized_lines(text: &str) -> Vec<&str> {
    text.lines().map(str::trim).filter(|s| !s.is_empty()).collect()
}

fn check_lock(root: &Path) -> Result<(), String> {
    let content = fs::read_to_string(root.join("Cargo.lock")).map_err(|e| e.to_string())?;
    if normalized_lines(&content) != normalized_lines(APPROVED_LOCK) {
        return Err("Dependency graph changed. The initial zero-external-package gate must not be weakened; implement and review full source/feature admission before adding foundations.".into());
    }
    println!("PASS reference_lock: exactly fa-reference and xtask; no external packages");
    Ok(())
}

fn check_source(root: &Path) -> Result<(), String> {
    for path in [
        "crates/fa-reference/src/lib.rs",
        "xtask/src/main.rs",
        "registry/foundation_audit.json",
        "docs/DEPENDENCY_CONSTITUTION.md",
        "docs/LOCAL_RELEASE.md",
        "COMPREHENSIVE_PLAN_FOR_THE_DESIGN_OF_FRANKENALIGNMENT.md",
    ] {
        if !root.join(path).is_file() {
            return Err(format!("Required file is missing: {path}"));
        }
    }
    for path in ["crates/fa-reference/src/lib.rs", "xtask/src/main.rs"] {
        let text = fs::read_to_string(root.join(path)).map_err(|e| e.to_string())?;
        if !text.contains("#![forbid(unsafe_code)]") {
            return Err(format!("Missing crate-level unsafe prohibition: {path}"));
        }
    }
    println!("PASS source_inventory: required files and crate-level prohibitions present");
    Ok(())
}

fn run(root: &Path, program: &str, arguments: &[&str]) -> Result<(), String> {
    println!("EXECUTE {program} {}", arguments.join(" "));
    let status = Command::new(program)
        .args(arguments)
        .current_dir(root)
        .status()
        .map_err(|e| format!("Cannot execute {program}: {e}"))?;
    if !status.success() {
        return Err(format!("{program} {} failed: {status}", arguments.join(" ")));
    }
    println!("PASS executed_command: {program} {}", arguments.join(" "));
    Ok(())
}

fn execute() -> Result<(), String> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .ok_or("Missing workspace parent")?
        .to_path_buf();
    let args: Vec<_> = env::args().skip(1).collect();
    match args.as_slice() {
        [command] if command == "check" => {
            check_lock(&root)?;
            check_source(&root)?;
            run(&root, "rustc", &["-Vv"])?;
            run(&root, "cargo", &["fmt", "--all", "--check"])?;
            run(&root, "cargo", &["check", "--workspace", "--all-targets", "--frozen"])?;
            run(&root, "cargo", &["clippy", "--workspace", "--all-targets", "--frozen", "--", "-D", "warnings"])?;
            run(&root, "cargo", &["test", "--workspace", "--all-targets", "--frozen"])?;
            println!("PASS local_reference_gate; not a production-readiness or signed-release claim");
            Ok(())
        }
        [command] if command == "inventory" => {
            check_lock(&root)?;
            check_source(&root)?;
            println!("INVENTORY ONLY: compilation, tests, source freezing and release verification were not performed by this command");
            Ok(())
        }
        [command] if command == "release-check" => {
            Err("Release blocked: no qualified production broker, frozen release toolchain, foundation closure, target matrix or signed proof closure exists in design draft 0.2.".into())
        }
        _ => Err("Usage: cargo xtask check | inventory | release-check".into()),
    }
}

fn main() -> ExitCode {
    match execute() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("FAIL: {error}");
            ExitCode::FAILURE
        }
    }
}
