//! Local gate driver. DSR owns the durable outer receipt and source freeze.
#![forbid(unsafe_code)]

mod admission;
mod admission_contract;
#[cfg(test)]
mod admission_evaluator_tests;
#[cfg(test)]
mod admission_negative_tests;
mod concordance;
#[cfg(test)]
mod concordance_tests;
mod json;
#[cfg(test)]
mod json_tests;
#[cfg(test)]
mod metadata_collection_tests;
#[cfg(test)]
mod metadata_path_tests;
mod prose_consistency;
#[cfg(test)]
mod prose_consistency_tests;
#[cfg(test)]
mod prose_input_tests;
mod registry_checks;
#[cfg(test)]
mod registry_negative_tests;
mod source_snapshot;
#[cfg(test)]
mod source_snapshot_tests;
mod system_map;
#[cfg(test)]
mod system_map_tests;
mod toolchain_identity;
#[cfg(test)]
mod workspace_root_tests;

use std::env;
use std::fs;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode, Stdio};

const APPROVED_LOCK: &str = r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "fa-reference"
version = "0.2.0"

[[package]]
name = "xtask"
version = "0.2.0"
"#;

fn normalized_lines(text: &str) -> Vec<&str> {
    text.lines()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .collect()
}

fn check_lock(root: &Path) -> Result<(), String> {
    let content = fs::read_to_string(root.join("Cargo.lock")).map_err(|e| e.to_string())?;
    if normalized_lines(&content) != normalized_lines(APPROVED_LOCK) {
        return Err("Dependency graph changed. The initial zero-external-package gate must not be weakened; implement and review full source/feature admission before adding foundations.".into());
    }
    println!("PASS reference_lock: exactly fa-reference and xtask; no external packages");
    Ok(())
}

fn check_source(root: &Path) -> Result<(), String> {
    for path in [
        "crates/fa-reference/src/lib.rs",
        "xtask/src/main.rs",
        "registry/foundation_audit.json",
        "docs/DEPENDENCY_CONSTITUTION.md",
        "docs/LOCAL_RELEASE.md",
        "COMPREHENSIVE_PLAN_FOR_THE_DESIGN_OF_FRANKENALIGNMENT.md",
    ] {
        if !root.join(path).is_file() {
            return Err(format!("Required file is missing: {path}"));
        }
    }
    for path in ["crates/fa-reference/src/lib.rs", "xtask/src/main.rs"] {
        let text = fs::read_to_string(root.join(path)).map_err(|e| e.to_string())?;
        if !text.contains("#![forbid(unsafe_code)]") {
            return Err(format!("Missing crate-level unsafe prohibition: {path}"));
        }
    }
    println!("PASS source_inventory: required files and crate-level prohibitions present");
    Ok(())
}

fn run(root: &Path, program: &str, arguments: &[&str]) -> Result<(), String> {
    println!("EXECUTE {program} {}", arguments.join(" "));
    let status = Command::new(program)
        .args(arguments)
        .current_dir(root)
        .status()
        .map_err(|e| format!("Cannot execute {program}: {e}"))?;
    if !status.success() {
        return Err(format!(
            "{program} {} failed: {status}",
            arguments.join(" ")
        ));
    }
    println!("PASS executed_command: {program} {}", arguments.join(" "));
    Ok(())
}

fn contained_file(root: &Path, value: &json::Json) -> Result<(), String> {
    let path = value
        .as_str()
        .ok_or("Metadata file path must be a string")?;
    let resolved = fs::canonicalize(path)
        .map_err(|error| format!("Cannot resolve metadata file {path}: {error}"))?;
    if !resolved.starts_with(root) || !resolved.is_file() {
        return Err(format!(
            "Metadata file escapes workspace or is not a file: {path}"
        ));
    }
    Ok(())
}

// This checks real filesystem identities at collection time. It does not claim
// a complete Rust include/module closure or protect against concurrent mutation;
// the outer operator source freeze is still required.
fn check_metadata_paths(root: &Path, bytes: &[u8]) -> Result<(), String> {
    let root = fs::canonicalize(root).map_err(|error| error.to_string())?;
    let document = json::parse(bytes, json::Limits::default())
        .map_err(|error| format!("Metadata parse failed: {error}"))?;
    let metadata_root = document
        .get("workspace_root")
        .and_then(json::Json::as_str)
        .ok_or("Metadata workspace root missing")?;
    if fs::canonicalize(metadata_root).map_err(|error| error.to_string())? != root {
        return Err("Metadata belongs to a different workspace".into());
    }
    let packages = document
        .get("packages")
        .and_then(json::Json::as_array)
        .ok_or("Metadata packages missing")?;
    for package in packages {
        contained_file(
            &root,
            package
                .get("manifest_path")
                .ok_or("Manifest path missing")?,
        )?;
        let targets = package
            .get("targets")
            .and_then(json::Json::as_array)
            .ok_or("Metadata target list missing")?;
        for target in targets {
            contained_file(
                &root,
                target.get("src_path").ok_or("Target source path missing")?,
            )?;
        }
    }
    Ok(())
}

fn collect_metadata(root: &Path, target: &str) -> Result<Vec<u8>, String> {
    collect_metadata_using(root, target, std::ffi::OsStr::new("cargo"))
}

// The program argument is operator/test infrastructure, never policy input.
// Keeping process creation here lets the absence test exercise the same path
// as the required live Cargo collection without altering global PATH.
fn collect_metadata_using(
    root: &Path,
    target: &str,
    program: &std::ffi::OsStr,
) -> Result<Vec<u8>, String> {
    let arguments = [
        "metadata",
        "--format-version",
        "1",
        "--locked",
        "--offline",
        "--filter-platform",
        target,
    ];
    let manifest = root.join("Cargo.toml");
    println!(
        "EXECUTE {} {} --manifest-path {}",
        program.to_string_lossy(),
        arguments.join(" "),
        manifest.display()
    );
    let output = Command::new(program)
        .args(arguments)
        .arg("--manifest-path")
        .arg(&manifest)
        .current_dir(root)
        .stderr(Stdio::inherit())
        .output()
        .map_err(|error| {
            format!("Cannot collect metadata for {target}: Unknown (spawn {program:?}: {error})")
        })?;
    if !output.status.success() {
        return Err(format!(
            "Metadata collection for {target} failed: Unknown (exit {})",
            output.status
        ));
    }
    Ok(output.stdout)
}

fn check_admission(root: &Path) -> Result<(), String> {
    let bytes = fs::read(root.join("registry/dependency_policy.json"))
        .map_err(|error| format!("Cannot read dependency policy: {error}"))?;
    let policy = admission::parse_policy(&bytes)?;
    for profile in &policy.profiles {
        let target = profile.target.as_str();
        let metadata = collect_metadata(root, target)?;
        let report = admission::check(&metadata, &policy, target)?;
        if !report.is_admitted() {
            print!("{}", report.render());
            return Err(format!("Dependency admission refused for {target}"));
        }
        check_metadata_paths(root, &metadata)?;
        print!("{}", report.render());
        println!(
            "PASS collected_metadata_paths[{target}]: actual workspace, manifests and target source files"
        );
    }
    Ok(())
}

fn check_toolchain(root: &Path) -> Result<(), String> {
    let policy_bytes = fs::read(root.join("registry/dependency_policy.json"))
        .map_err(|error| format!("Cannot read toolchain qualification: {error}"))?;
    let policy = json::parse(&policy_bytes, json::Limits::default())
        .map_err(|error| format!("Invalid qualification policy: {error}"))?;
    let qualification = policy
        .get("operator_qualification")
        .ok_or("Missing operator toolchain qualification")?;
    let expected_commit = qualification
        .get("rustc_commit")
        .and_then(json::Json::as_str)
        .ok_or("Missing qualified rustc commit")?;
    let expected_host = qualification
        .get("host")
        .and_then(json::Json::as_str)
        .ok_or("Missing qualified operator host")?;
    println!("EXECUTE rustc -Vv");
    let output = Command::new("rustc")
        .arg("-Vv")
        .current_dir(root)
        .stderr(Stdio::inherit())
        .output()
        .map_err(|error| format!("Cannot collect rustc identity: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "rustc identity collection failed: {}",
            output.status
        ));
    }
    std::io::stdout()
        .write_all(&output.stdout)
        .map_err(|error| format!("Cannot retain rustc identity output: {error}"))?;
    toolchain_identity::check_verbose_version(&output.stdout, expected_commit, expected_host)?;
    println!(
        "PASS qualified_rustc_identity: {expected_commit} on {expected_host}; compiler-reported identity only"
    );
    Ok(())
}

fn check_registries(root: &Path) -> Result<(), String> {
    let report = registry_checks::check_repository(root);
    for finding in &report.findings {
        eprintln!(
            "REFUSE registry[{}] {} {} {}: {}",
            finding.file,
            finding.id.as_deref().unwrap_or("<document>"),
            finding.code,
            finding.location,
            finding.detail
        );
    }
    if !report.is_clean() {
        return Err(format!(
            "Registry core refused {} structural findings",
            report.findings.len()
        ));
    }
    println!(
        "PASS registry_core: IDs, roadmap DAG, declared links, retained files and scoped source test declarations; not execution or invariant proof"
    );
    Ok(())
}

fn check_source_snapshot(root: &Path) -> Result<source_snapshot::Manifest, String> {
    let policy_bytes = fs::read(root.join("registry/dependency_policy.json"))
        .map_err(|error| format!("Cannot read admission contract: {error}"))?;
    let policy = json::parse(&policy_bytes, json::Limits::default())
        .map_err(|error| format!("Invalid admission contract: {error}"))?;
    let binding = admission_contract::check(&policy)?;
    source_snapshot::verify_manifest_identity(root, &binding.manifest_path, &binding.sha256)?;
    println!(
        "PASS admission_contract: required local source, target, build/runtime review and future external constraints; snapshot identity matched"
    );
    let limits = source_snapshot::Limits::default();
    let mut bytes = Vec::new();
    fs::File::open(root.join(&binding.manifest_path))
        .map_err(|error| format!("Cannot open reviewed source snapshot: {error}"))?
        .take(limits.max_manifest_bytes as u64 + 1)
        .read_to_end(&mut bytes)
        .map_err(|error| format!("Cannot read reviewed source snapshot: {error}"))?;
    let manifest = source_snapshot::parse_manifest(&bytes, limits)?;
    let report = source_snapshot::verify(root, &manifest, limits)?;
    print!("{}", report.render());
    if !report.is_verified() {
        return Err("Reviewed source snapshot refused current source/build input bytes".into());
    }
    Ok(manifest)
}

const PLAN_INPUT: &str = "COMPREHENSIVE_PLAN_FOR_THE_DESIGN_OF_FRANKENALIGNMENT.md";
const CONCORDANCE_INPUT_LIMIT: usize = 4 * 1024 * 1024;

fn read_concordance_input(
    root: &Path,
    manifest: &source_snapshot::Manifest,
    relative: &str,
) -> Result<Vec<u8>, String> {
    let digest = manifest
        .digest(relative)
        .ok_or_else(|| format!("Concordance input is outside the verified snapshot: {relative}"))?;
    let mut bytes = Vec::new();
    fs::File::open(root.join(relative))
        .map_err(|error| format!("Cannot open concordance input {relative}: {error}"))?
        .take(CONCORDANCE_INPUT_LIMIT as u64 + 1)
        .read_to_end(&mut bytes)
        .map_err(|error| format!("Cannot read concordance input {relative}: {error}"))?;
    if bytes.len() > CONCORDANCE_INPUT_LIMIT {
        return Err(format!("Concordance input exceeds byte limit: {relative}"));
    }
    println!(
        "CONCORDANCE input={relative} bytes={} sha256={digest}; verified source manifest, outer freeze required",
        bytes.len()
    );
    Ok(bytes)
}

fn check_concordance(root: &Path, manifest: &source_snapshot::Manifest) -> Result<(), String> {
    let load_json = |relative: &str| -> Result<json::Json, String> {
        let bytes = read_concordance_input(root, manifest, relative)?;
        json::parse(&bytes, json::Limits::default())
            .map_err(|error| format!("Invalid concordance input {relative}: {error}"))
    };
    let concordance = load_json("registry/founding_concordance.json")?;
    let invariants = load_json("registry/invariants.json")?;
    let claims = load_json("registry/claims.json")?;
    let roadmap = load_json("registry/roadmap.json")?;
    let plan_bytes = read_concordance_input(root, manifest, PLAN_INPUT)?;
    let plan = std::str::from_utf8(&plan_bytes)
        .map_err(|error| format!("Invalid UTF-8 in {PLAN_INPUT}: {error}"))?;
    let report = concordance::check(&concordance, &invariants, &claims, &roadmap, plan);
    // The operator retains this exact JSON under the artifact's concordance key
    // after execution. The gate never writes logs into its frozen source root.
    println!("CONCORDANCE_JSON {}", report.render_json());
    if !report.is_clean() {
        return Err("Concordance coverage refused; exact findings are in CONCORDANCE_JSON".into());
    }
    println!(
        "PASS concordance: direct typed coverage and reference validity; not implementation or invariant proof"
    );
    Ok(())
}

// Resolve the invocation's checkout, never a compile-time temporary archive.
// Cargo runs xtask tests in the xtask crate; operator commands run at the root.
// Deliberately do not search arbitrary ancestors for another workspace.
fn workspace_root_from(start: &Path) -> Result<PathBuf, String> {
    let start = fs::canonicalize(start).map_err(|error| {
        format!(
            "Cannot resolve invocation directory {}: {error}",
            start.display()
        )
    })?;
    let has_manifests = |candidate: &Path| {
        candidate.join("Cargo.toml").is_file() && candidate.join("xtask/Cargo.toml").is_file()
    };
    if has_manifests(&start) {
        return Ok(start);
    }
    if start.file_name() == Some(std::ffi::OsStr::new("xtask"))
        && let Some(parent) = start.parent()
        && has_manifests(parent)
    {
        return Ok(parent.to_path_buf());
    }
    Err(format!(
        "Run xtask from the workspace root or its immediate xtask directory; {} is neither",
        start.display()
    ))
}

fn workspace_root() -> Result<PathBuf, String> {
    workspace_root_from(
        &env::current_dir()
            .map_err(|error| format!("Cannot read invocation directory: {error}"))?,
    )
}

fn current_execution_receipt(status: &str) -> Result<&str, String> {
    let mut declarations = concordance::unfenced_markdown_lines(status)
        .into_iter()
        .filter(|line| line.starts_with("Current execution evidence:"));
    let declaration = declarations
        .next()
        .ok_or("Missing current execution evidence declaration")?;
    if declarations.next().is_some() {
        return Err("Ambiguous current execution evidence declaration".into());
    }
    let receipt = declaration
        .strip_prefix("Current execution evidence: [receipt](")
        .and_then(|line| line.strip_suffix(")."))
        .ok_or("Malformed current execution evidence declaration")?;
    let filename = receipt
        .strip_prefix("artifacts/execution/")
        .ok_or("Current execution receipt must be under artifacts/execution")?;
    if filename.len() > 255
        || !filename.ends_with("-receipt.json")
        || !filename
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
    {
        return Err("Current execution receipt must name one canonical receipt file".into());
    }
    Ok(receipt)
}

fn read_prose_input(root: &Path, relative: &str) -> Result<Vec<u8>, String> {
    read_operator_input(root, relative, "PROSE", "Prose")
}

fn read_operator_input(
    root: &Path,
    relative: &str,
    label: &str,
    kind: &str,
) -> Result<Vec<u8>, String> {
    const LIMIT: u64 = 4 * 1024 * 1024;
    let path = root.join(relative);
    if fs::metadata(&path)
        .map_err(|error| format!("Cannot inspect {relative}: {error}"))?
        .len()
        > LIMIT
    {
        return Err(format!("{kind} input exceeds {LIMIT} bytes: {relative}"));
    }
    let digest = source_snapshot::operator_file_digest(root, relative)?;
    let mut bytes = Vec::new();
    fs::File::open(&path)
        .map_err(|error| format!("Cannot read {relative}: {error}"))?
        .take(LIMIT + 1)
        .read_to_end(&mut bytes)
        .map_err(|error| format!("Cannot read {relative}: {error}"))?;
    if bytes.len() as u64 > LIMIT {
        return Err(format!(
            "{kind} input grew beyond {LIMIT} bytes: {relative}"
        ));
    }
    println!(
        "{label} input={relative} bytes={} sha256={digest}; operator digest and outer freeze, not receipt authentication",
        bytes.len()
    );
    Ok(bytes)
}

fn check_prose(root: &Path) -> Result<(), String> {
    let text = |relative: &str| -> Result<String, String> {
        String::from_utf8(read_prose_input(root, relative)?)
            .map_err(|error| format!("Invalid UTF-8 in {relative}: {error}"))
    };
    let document = |relative: &str| -> Result<json::Json, String> {
        json::parse(&read_prose_input(root, relative)?, json::Limits::default())
            .map_err(|error| format!("Invalid JSON in {relative}: {error}"))
    };
    let readme = text("README.md")?;
    let status = text("IMPLEMENTATION_STATUS.md")?;
    let receipt = document(current_execution_receipt(&status)?)?;
    let concordance = document("registry/founding_concordance.json")?;
    let invariants = document("registry/invariants.json")?;
    let claims = document("registry/claims.json")?;
    let roadmap = document("registry/roadmap.json")?;
    let plan = text(PLAN_INPUT)?;
    let report = prose_consistency::check(prose_consistency::Inputs {
        readme: &readme,
        status: &status,
        concordance: &concordance,
        invariants: &invariants,
        claims: &claims,
        roadmap: &roadmap,
        plan: &plan,
        receipt: &receipt,
    });
    println!("PROSE_JSON {}", report.render_json());
    if !report.is_clean() {
        return Err("Current prose consistency refused; exact findings are in PROSE_JSON".into());
    }
    println!(
        "PASS prose_consistency: current declarations match registries and the named retained receipt; not new-source execution proof"
    );
    Ok(())
}

fn check_system_map(root: &Path) -> Result<(), String> {
    let text = |relative: &str| -> Result<String, String> {
        String::from_utf8(read_operator_input(
            root,
            relative,
            "SYSTEM_MAP",
            "System-map",
        )?)
        .map_err(|error| format!("Invalid UTF-8 in {relative}: {error}"))
    };
    let document = |relative: &str| -> Result<json::Json, String> {
        json::parse(
            &read_operator_input(root, relative, "SYSTEM_MAP", "System-map")?,
            json::Limits::default(),
        )
        .map_err(|error| format!("Invalid JSON in {relative}: {error}"))
    };
    let system_map = document("registry/system_map.json")?;
    let vocabulary = document("registry/vocabulary.json")?;
    let invariants = document("registry/invariants.json")?;
    let roadmap = document("registry/roadmap.json")?;
    let readme = text("README.md")?;
    let agent_guide = text("docs/AGENT_GUIDE.md")?;
    let system_map_doc = text("docs/SYSTEM_MAP.md")?;
    let beads_issues = text(".beads/issues.jsonl")?;
    let plan = text(PLAN_INPUT)?;
    let report = system_map::check(system_map::Inputs {
        system_map: &system_map,
        vocabulary: &vocabulary,
        invariants: &invariants,
        roadmap: &roadmap,
        readme: &readme,
        agent_guide: &agent_guide,
        system_map_doc: &system_map_doc,
        beads_issues: &beads_issues,
        plan: &plan,
    });
    println!("SYSTEM_MAP_JSON {}", report.render_json());
    if !report.is_clean() {
        return Err("System-map consistency refused; exact findings are in SYSTEM_MAP_JSON".into());
    }
    println!(
        "PASS system_map: bounded registry/document consistency and checker-epic bead link; no command or layer-suite execution claim"
    );
    Ok(())
}

fn execute() -> Result<(), String> {
    let root = workspace_root()?;
    let args: Vec<_> = env::args().skip(1).collect();
    match args.as_slice() {
        [command] if command == "check" => {
            check_lock(&root)?;
            check_source(&root)?;
            check_toolchain(&root)?;
            let manifest = check_source_snapshot(&root)?;
            check_admission(&root)?;
            check_registries(&root)?;
            check_concordance(&root, &manifest)?;
            check_system_map(&root)?;
            check_prose(&root)?;
            run(&root, "cargo", &["fmt", "--all", "--check"])?;
            run(&root, "cargo", &["check", "--workspace", "--all-targets", "--frozen"])?;
            run(&root, "cargo", &["clippy", "--workspace", "--all-targets", "--frozen", "--", "-D", "warnings"])?;
            run(&root, "cargo", &["test", "--workspace", "--all-targets", "--frozen"])?;
            run(&root, "cargo", &["test", "--workspace", "--doc", "--frozen"])?;
            println!("PASS local_reference_gate; not a production-readiness or signed-release claim");
            Ok(())
        }
        [command] if command == "inventory" => {
            check_lock(&root)?;
            check_source(&root)?;
            println!("INVENTORY ONLY: compilation, tests, source freezing and release verification were not performed by this command");
            Ok(())
        }
        [command] if command == "concordance-check" => {
            let manifest = check_source_snapshot(&root)?;
            check_concordance(&root, &manifest)
        }
        [command] if command == "prose-check" => {
            let _manifest = check_source_snapshot(&root)?;
            check_prose(&root)
        }
        [command] if command == "system-map-check" => {
            let _manifest = check_source_snapshot(&root)?;
            check_system_map(&root)
        }
        [command] if command == "release-check" => {
            Err("Release blocked: no qualified production broker, frozen release toolchain, foundation closure, target matrix or signed proof closure exists yet.".into())
        }
        _ => Err("Usage: cargo xtask check | concordance-check | system-map-check | prose-check | inventory | release-check".into()),
    }
}

fn main() -> ExitCode {
    match execute() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("FAIL: {error}");
            ExitCode::FAILURE
        }
    }
}
